PCstore.Web/ViewModels/Device/ComputerViewModel.cs
using PCstore.Data.Model;
using PCstore.Web.Infrastructure;
using System;
using AutoMapper;
using System.ComponentModel.DataAnnotations;

namespace PCstore.Web.ViewModels.Device
{
    public class ComputerViewModel : IMapFrom<Computer>, IHaveCustomMappings, IDeviceViewModel
    {
        public Guid Id { get; set; }


        [Required]
        [MinLength(10)]
        [MaxLength(30)]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        public string CPU { get; set; }


        [Required]
        [Display(Name = "CPU Speed")]
        [Range(1d, 5d, ErrorMessage = "CPU speed must be between 1 and 5 Ghz decimal number")]
        public double CpuSpeed { get; set; }


        [Required]
        [Range(1, 64, ErrorMessage = "RAM must be between 1 and 64 GB integer number")]
        public int RAM { get; set; }


        [Required]
        [MinLength(1)]
        [MaxLength(10)]
        [Display(Name = "Ram Type")]
        [StringLength(10, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 1)]
        public string RamType { get; set; }


        [Required]
        [Range(1, 2000, ErrorMessage = "HDD must be between 1 and 2000 GB integer number")]
        public int HDD { get; set; }


        [Required]
        [MinLength(10)]
        [MaxLength(30)]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        public string GPU { get; set; }


        [Required]
        [Display(Name = "GPU Memory")]
        [Range(1, 8, ErrorMessage = "GPU Memory must be between 1 and 8 integer number")]
        public int GpuMemory { get; set; }


        [Required]
        [MinLength(4)]
        [MaxLength(30)]
        [Display(Name = "Optical Device")]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 4)]
        public string OpticalDevice { get; set; }


        [Required]
        [MinLength(4)]
        [MaxLength(20)]
        [Display(Name = "Operating System")]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 4)]
        public string OperatingSystem { get; set; }


        [Required]
        [Range(1, 10000, ErrorMessage = "Price must be between 1 and 10000 decimal number")]
        public decimal Price { get; set; }


        [Required]
        [MinLength(8)]
        [MaxLength(12)]
        [Display(Name = "Seller Phone")]
        [StringLength(12, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 8)]
        public string SellerPhone { get; set; }


        [Required]
        [MinLength(1)]
        [MaxLength(500)]
        [StringLength(500, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 1)]
        public string Description { get; set; }


        [Required]
        public virtual User Seller { get; set; }


        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime CreatedOn { get; set; }


        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime PostedOn { get; set; }


        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<Computer, ComputerViewModel>()
                .ForMember(viewModel => viewModel.PostedOn, cfg => cfg.MapFrom(model => model.ModifiedOn));
        }
    }
}

PCstore.Web/ViewModels/Device/DevicesViewModel.cs
using System.Collections.Generic;

namespace PCstore.Web.ViewModels.Device
{
    public class DevicesViewModel
    {
        public ICollection<ComputerViewModel> Computers { get; set; }
        public ICollection<LaptopViewModel> Laptops { get; set; }
        public ICollection<DisplayViewModel> Displays { get; set; }
    }
}

PCstore.Web/ViewModels/Device/DisplayViewModel.cs
using PCstore.Data.Model;
using PCstore.Web.Infrastructure;
using System;
using System.ComponentModel.DataAnnotations;
using AutoMapper;

namespace PCstore.Web.ViewModels.Device
{
    public class DisplayViewModel : IMapFrom<Display>, IHaveCustomMappings, IDeviceViewModel
    {
        public Guid Id { get; set; }


        [Required]
        [Display(Name = "Display Size")]
        [Range(1d, 19d, ErrorMessage = "Display size must be between 1 and 19 inch decimal number")]
        public double Size { get; set; }


        [Required]
        [MinLength(7)] //800x600
        [MaxLength(9)] //1920x1024 
        [Display(Name = "Display Resolution")]
        [StringLength(9, ErrorMessage = "The {0} must be at least {2} characters long in format 1920x1024", MinimumLength = 7)]
        public string Resolution { get; set; }


        [Required]
        [MinLength(1)]
        [MaxLength(5)]
        [StringLength(5, ErrorMessage = "The {0} must be between {2} and 5 characters long", MinimumLength = 1)]
        public string Type { get; set; }


        [Required]
        [Range(256000d, 17000000d, ErrorMessage = "Colors must be between 256 k and 17 mil decimal number")]
        public double Colors { get; set; }


        [Required]
        [Range(1, 10000, ErrorMessage = "Price must be between 1 and 10000 decimal number")]
        public decimal Price { get; set; }


        [Required]
        [MinLength(8)]
        [MaxLength(12)]
        [Display(Name = "Seller Phone")]
        [StringLength(12, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 8)]
        public string SellerPhone { get; set; }


        [Required]
        [MinLength(1)]
        [MaxLength(500)]
        [StringLength(500, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 1)]
        public string Description { get; set; }


        [Required]
        public virtual User Seller { get; set; }


        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime CreatedOn { get; set; }


        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime PostedOn { get; set; }


        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<Display, DisplayViewModel>()
                .ForMember(viewModel => viewModel.PostedOn, cfg => cfg.MapFrom(model => model.ModifiedOn));
        }
    }
}

PCstore.Web/ViewModels/Device/IDeviceViewModel.cs
using PCstore.Data.Model;
using System;

namespace PCstore.Web.ViewModels.Device
{
    public interface IDeviceViewModel
    {
        Guid Id { get; set; }
        decimal Price { get; set; }
        string SellerPhone { get; set; }
        User Seller { get; set; }
        string Description { get; set; }
        DateTime CreatedOn { get; set; }
        DateTime PostedOn { get; set; }       
    }
}

PCstore.Web/Controllers/DeviceController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using PCstore.Data.Model;
using PCstore.Services.Contracts;
using PCstore.Web.ViewModels.Device;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Caching;
using PagedList;
using Bytes2you.Validation;
using PCstore.Web.Providers.Contracts;

namespace PCstore.Web.Controllers
{
    public class DeviceController : Controller
    {
        private readonly IVerificationProvider verification;
        private readonly IMapper mapper;
        private readonly IUsersService usersService;
        private readonly IComputersService computersService;
        private readonly ILaptopsService laptopsService;
        private readonly IDisplaysService displaysService;

        public DeviceController()
        {
        }

        public DeviceController(IVerificationProvider verification, IMapper mapper, IUsersService usersService,
            IComputersService computersService, ILaptopsService laptopsService, IDisplaysService displaysService)
        {
            Guard.WhenArgument(verification, nameof(verification)).IsNull().Throw();
            Guard.WhenArgument(mapper, nameof(mapper)).IsNull().Throw();
            Guard.WhenArgument(usersService, nameof(usersService)).IsNull().Throw();
            Guard.WhenArgument(computersService, nameof(computersService)).IsNull().Throw();
            Guard.WhenArgument(laptopsService, nameof(laptopsService)).IsNull().Throw();
            Guard.WhenArgument(displaysService, nameof(displaysService)).IsNull().Throw();

            this.verification = verification;
            this.mapper = mapper;
            this.usersService = usersService;
            this.computersService = computersService;
            this.laptopsService = laptopsService;
            this.displaysService = displaysService;
        }


        // COMPUTERS \\
        [HttpGet]
        [OutputCache(CacheProfile = "ShortLived")]
        public ActionResult Computers(int? page)
        {
            ViewData["Title"] = "Computers";

            var computers = this.computersService
                .GetAll()
                .OrderByDescending(x => x.ModifiedOn)
                .ProjectTo<ComputerViewModel>()
                .ToList();

            var viewModel = new DevicesViewModel()
            {
                Computers = computers
            };

            var pageNumber = page ?? 1;
            var pageSize = 10;
            return View(viewModel.Computers.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Computer(Guid Id)
        {
            ViewData["Title"] = "Computer";

            var computer = this.computersService
                .GetAll()
                .ProjectTo<ComputerViewModel>()
                .Single(x => x.Id == Id);

            return View(computer);
        }

        // Add Computer \\
        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public ActionResult AddComputer()
        {
            ViewData["Title"] = "Create Computer Advertisement";
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult AddComputer(Computer model)
        {
            var userId = this.verification.CurrentUserId;
            var currentUser = this.usersService.GetAll()
                           .Single(x => x.Id == userId);

            model.CreatedOn = DateTime.Now;
            model.Seller = currentUser;
            this.computersService.Add(model);

            return RedirectToAction("Index", "Manage");
        }

        // Update Computer \\
        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public ActionResult UpdateComputer(Guid id)
        {
            ViewData["Title"] = "Update Computer Advertisement";

            var computer = this.computersService
                .GetAll()
                .ProjectTo<ComputerViewModel>()
                .Single(x => x.Id == id);

            return View(computer);
        }

        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateComputer(Computer model)
        {
            this.computersService.Update(model);

            return RedirectToAction("Index", "Manage");
        }

        // LAPTOPS \\
        [HttpGet]
        [OutputCache(CacheProfile = "ShortLived")]
        public ActionResult Laptops(int? page)
        {
            ViewData["Title"] = "Laptops";

            var laptops = this.laptopsService
               .GetAll()
               .OrderByDescending(x => x.ModifiedOn)
               .ProjectTo<LaptopViewModel>()
               .ToList();

            var viewModel = new DevicesViewModel()
            {
                Laptops = laptops
            };

            var pageNumber = page ?? 1;
            var pageSize = 10;
            return View(viewModel.Laptops.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Laptop(Guid Id)
        {
            ViewData["Title"] = "Laptop";

            var laptop = this.laptopsService
                 .GetAll()
                 .ProjectTo<LaptopViewModel>()
                 .Single(x => x.Id == Id);

            return View(laptop);
        }

        // Add Laptop \\
        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public ActionResult AddLaptop()
        {
            ViewData["Title"] = "Create Laptop Advertisement";
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult AddLaptop(Laptop model)
        {
            var userId = this.verification.CurrentUserId;
            var currentUser = this.usersService.GetAll()
                           .Single(x => x.Id == userId);

            model.CreatedOn = DateTime.Now;
            model.Seller = currentUser;
            this.laptopsService.Add(model);

            return RedirectToAction("Index", "Manage");
        }

        // Update Laptop \\
        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public ActionResult UpdateLaptop(Guid id)
        {
            ViewData["Title"] = "Update Laptop Advertisement";

            var laptop = this.laptopsService
                .GetAll()
                .ProjectTo<LaptopViewModel>()
                .Single(x => x.Id == id);

            return View(laptop);
        }

        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateLaptop(Laptop model)
        {
            this.laptopsService.Update(model);

            return RedirectToAction("Index", "Manage");
        }

        // DISPLAYS \\
        [HttpGet]
        [OutputCache(CacheProfile = "ShortLived")]
        public ActionResult Displays(int? page)
        {
            ViewData["Title"] = "Displays";

            var displays = this.displaysService
               .GetAll()
               .OrderByDescending(x => x.ModifiedOn)
               .ProjectTo<DisplayViewModel>()
               .ToList();

            var viewModel = new DevicesViewModel()
            {
                Displays = displays
            };

            var pageNumber = page ?? 1;
            var pageSize = 10;
            return View(viewModel.Displays.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Display(Guid Id)
        {
            ViewData["Title"] = "Display";

            var display = this.displaysService
                   .GetAll()
                   .ProjectTo<DisplayViewModel>()
                   .Single(x => x.Id == Id);

            return View(display);
        }

        // Add Display \\
        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public ActionResult AddDisplay()
        {
            ViewData["Title"] = "Create Display Advertisement";
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult AddDisplay(Display model)
        {
            var userId = this.verification.CurrentUserId;
            var currentUser = this.usersService.GetAll()
                           .Single(x => x.Id == userId);

            model.CreatedOn = DateTime.Now;
            model.Seller = currentUser;
            this.displaysService.Add(model);

            return RedirectToAction("Index", "Manage");
        }

        // Update Display \\
        [HttpGet]
        [Authorize(Roles = "User, Admin")]
        public ActionResult UpdateDisplay(Guid id)
        {
            ViewData["Title"] = "Update Display Advertisement";

            var display = this.displaysService
                .GetAll()
                .ProjectTo<DisplayViewModel>()
                .Single(x => x.Id == id);

            return View(display);
        }

        [HttpPost]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateDisplay(Display model)
        {
            this.displaysService.Update(model);

            return RedirectToAction("Index", "Manage");
        }
    }
}

PCstore.Web/Views/Device/AddComputer.cshtml
@model ComputerViewModel

@Styles.Render("~/Content/nooverflow")

<h3 align="center">@ViewData["Title"]</h3>

<div class="container">
    @using (Html.BeginForm("AddComputer", "Device", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <h4>Add new computer advertisement</h4>
        <hr />

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(x => x.CPU, "CPU Name", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.CPU, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.CPU, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.CpuSpeed, "CPU Speed (Ghz)", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.CpuSpeed, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.CpuSpeed, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @{
                    var ram = new List<int>() { 4, 8, 16, 32, 64 };
                }
                @Html.LabelFor(x => x.RAM, "RAM (GB)", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.DropDownListFor(x => x.RAM, new SelectList(ram), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.RAM, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @{
                    var ramTypesList = new List<string>() { "DDR", "DDR2", "DDR3", "DDR4" };
                }
                @Html.LabelFor(x => x.RamType, "Ram Type", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.DropDownListFor(x => x.RamType, new SelectList(ramTypesList), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.RamType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.HDD, "HDD (GB)", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.HDD, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.HDD, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.GPU, "GPU Name", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.GPU, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.GPU, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @{
                    var gpuMemory = new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8 };
                }
                @Html.LabelFor(x => x.GpuMemory, "GPU Memory (GB)", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.DropDownListFor(x => x.GpuMemory, new SelectList(gpuMemory), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.GpuMemory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.OpticalDevice, "Optical Device", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.OpticalDevice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.OpticalDevice, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.OperatingSystem, "Operating System", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.OperatingSystem, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.OperatingSystem, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Price, "Price (€)", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.SellerPhone, "Seller Phone", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.SellerPhone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.SellerPhone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Description, "Description", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-5 col-md-8">
                <input type="submit" class="btn btn-primary" value="@ViewData["Title"]" />
            </div>
        </div>
                    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PCstore.Web/Views/Device/AddDisplay.cshtml
@model DisplayViewModel

@Styles.Render("~/Content/nooverflow")

<h3 align="center">@ViewData["Title"]</h3>

<div class="container">
    @using (Html.BeginForm("AddDisplay", "Device", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <h4>Add new display advertisement</h4>
        <hr />

        <div class="col-md-6">
            <div class="form-group">
                @{
                    var displays = new List<double>() { 12, 13.3, 14, 15.4, 15.6, 17, 19 };
                }
                @Html.LabelFor(x => x.Size, "Display Size (inch)", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.DropDownListFor(x => x.Size, new SelectList(displays), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Size, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Resolution, "Display Resolution", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.Resolution, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Resolution, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @{
                    var types = new List<string>() { "LCD", "TFT", "IPS", "LED" };
                }
                @Html.LabelFor(x => x.Type, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.DropDownListFor(x => x.Type, new SelectList(types), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Type, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @{
                    var colors = new List<double>() { 256000, 1240000, 6340000, 12520000, 16700000 };
                }
                @Html.LabelFor(x => x.Colors, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.DropDownListFor(x => x.Colors, new SelectList(colors), new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Colors, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Price, "Price (€)", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.SellerPhone, "Seller Phone", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.SellerPhone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.SellerPhone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Description, "Description", new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-5 col-md-8">
                <input type="submit" class="btn btn-info" value="@ViewData["Title"]" />
            </div>
        </div>
                    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PCstore.Web/Views/Device/Computers.cshtml
@using PagedList.Mvc;
@using PagedList;

@model IPagedList<ComputerViewModel>

@Styles.Render("~/Content/advertisement")

<h3 align="center">@ViewData["Title"]</h3>

<div class="container">

    @foreach (var computer in Model)
    {
        <div class="row">
            <a class="list-group-item clearfix" href="@Url.Action("Computer", "Device",  new { computer.Id }, null)">
                <div class="col-md-3">
                    <img class="media-object" src="~/Images/image4.png" width="120">
                </div>
                <div class="col-md-3">
                    <p><strong>CPU: </strong>@computer.CPU</p>
                    <p><strong>CPU Speed: </strong>@computer.CpuSpeed Ghz</p>
                    <p><strong>RAM: </strong>@computer.RAM GB</p>
                </div>
                <div class="col-md-3">
                    <p><strong>RAM Type: </strong>@computer.RamType</p>
                    <p><strong>HDD: </strong>@computer.HDD GB</p>
                    <p><strong>GPU: </strong>@computer.GPU</p>
                </div>
                <div class="col-md-3">
                    <p><strong>GPU Memory: </strong>@computer.GpuMemory GB</p>
                    <p><strong>Price: </strong>@computer.Price €</p>
                    <p>
                        <strong>Posted On: </strong>@Html.DisplayFor(x => computer.PostedOn)
                    </p>
                </div>
            </a>
        </div>
    }
</div>

<div align="center">
    @Html.PagedListPager(Model, page => Url.Action("Computers", new { page }))
</div>

PCstore.Web/Views/Device/Displays.cshtml
@using PagedList.Mvc;
@using PagedList;

@model IPagedList<DisplayViewModel>

@Styles.Render("~/Content/advertisement")

<h3 align="center">@ViewData["Title"]</h3>

<div class="container">

    @foreach (var display in Model)
    {
        <div class="row">
            <a class="list-group-item clearfix" href="@Url.Action("Display", "Device",  new { display.Id }, null)">
                <div class="col-md-3">
                    <img class="media-object" src="~/Images/image8.png" width="120">
                </div>
                <div class="col-md-3">
                    <p><strong>Size: </strong>@display.Size "</p>
                    <p><strong>Resolution: </strong>@display.Resolution</p>
                    <p><strong>Type: </strong>@display.Type</p>
                </div>
                <div class="col-md-3">
                    <p><strong>Colors: </strong>@display.Colors</p>
                    <p><strong>Price: </strong>@display.Price €</p>
                    <p><strong>Posted On: </strong>@Html.DisplayFor(x => display.PostedOn)</p>
                </div>
            </a>
        </div>
    }
</div>

<div align="center">
    @Html.PagedListPager(Model, page => Url.Action("Displays", new { page }))
</div>

PCstore.Web/Views/Device/Laptops.cshtml
@using PagedList.Mvc;
@using PagedList;

@model IPagedList<LaptopViewModel>

@Styles.Render("~/Content/advertisement")

<h3 align="center">@ViewData["Title"]</h3>

<div class="container">

    @foreach (var laptop in Model)
    {
        <div class="row">
            <a class="list-group-item clearfix" href="@Url.Action("Laptop", "Device",  new { laptop.Id }, null)">
                <div class="col-md-3">
                    <img class="media-object" src="~/Images/image7.png" width="120">
                </div>
                <div class="col-md-3">
                    <p><strong>Display: </strong>@laptop.DisplaySize "</p>
                    <p><strong>CPU: </strong>@laptop.CPU</p>
                    <p><strong>CPU Speed: </strong>@laptop.CpuSpeed Ghz</p>
                </div>
                <div class="col-md-3">
                    <p><strong>RAM: </strong>@laptop.RAM GB</p>
                    <p><strong>HDD: </strong>@laptop.HDD GB</p>
                    <p><strong>GPU: </strong>@laptop.GPU</p>
                </div>
                <div class="col-md-3">
                    <p><strong>GPU Memory: </strong>@laptop.GpuMemory GB</p>
                    <p><strong>Price: </strong>@laptop.Price €</p>
                    <p>
                        <strong>Posted On: </strong>@Html.DisplayFor(x => laptop.PostedOn)
                    </p>
                </div>
            </a>
        </div>
    }
</div>

<div align="center">
    @Html.PagedListPager(Model, page => Url.Action("Laptops", new { page }))
</div>